# Generated by Django 5.2.1 on 2025-05-20 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrazilState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("abbreviation", models.CharField(max_length=2)),
                ("map_x_position", models.FloatField()),
                ("map_y_position", models.FloatField()),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("norte", "Norte"),
                            ("nordeste", "Nordeste"),
                            ("centro-oeste", "Centro-Oeste"),
                            ("sudeste", "Sudeste"),
                            ("sul", "Sul"),
                        ],
                        default="norte",
                        max_length=15,
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("extension", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                            ("expert", "Especialista"),
                            ("final", "Desafio Final"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.IntegerField()),
                ("input_description", models.TextField()),
                ("output_description", models.TextField()),
                ("example_input", models.TextField()),
                ("example_output", models.TextField()),
                ("test_cases", models.JSONField(default=list)),
                ("time_limit", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge",
                        to="challenges.brazilstate",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.programminglanguage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Em Execução"),
                            ("accepted", "Aceito"),
                            ("wrong_answer", "Resposta Incorreta"),
                            ("time_limit", "Tempo Limite Excedido"),
                            ("compilation_error", "Erro de Compilação"),
                            ("runtime_error", "Erro de Execução"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.programminglanguage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
